//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.Extension.Library.Domain.Model
{
    using System;
    
    public partial class Audit
    {
        public System.DateTime Updated { get; set; }
        public string User { get; set; }
        public System.DateTime Created { get; set; }
    }
}
